### ISSUE TITLE
Editor position is lost on refocus of Editor from within Moony

### ISSUE THREAD

**Issue by mxmilkb** [OpenMusicKontrollers/moony.lv2#5] opened 2018-02-20 19:06 UTC
Which makes editing rather frustrating!

**Comment by ventosus** [comment] 2018-02-20 20:38
I can reproduce that.

Focus jumping back after a save would be great, indeed.

Don't know whether restoring editor position upon a load makes any sense, though...

**Comment by ventosus** [comment] 2018-02-20 20:56
Hmm, just out of curiosity.

Why is this frustrating, do you need to save/load that often, if yes, why?

I'm just interested in your use case, as I neither use save nor load...

fyi, there's an alternative UI which just spawns your favorite editor, see issue #3 on how to activate it.

**Comment by milkmiruku** [comment] 2018-02-20 22:09
I'm trying to grok the flow of saving state, to file at first, though I realise now that saving Parameter state as a file saves the whole script + parameter state, overwriting code changes. I'll look at stashing for now instead.

Frustrating because, I realise now, the text position actually resets every time I click back into the Editor. I was just testing with Save and Load at the time and confused the two.

I'll have a look at using an external editor shortly, thanks!

**Comment by milkmiruku** [comment] 2018-02-20 23:09
(position isn't lost when focus is switched to/from an external window)

**Comment by ventosus** [comment] 2018-02-21 06:42
> I'm trying to grok the flow of saving state

Save/Load only save/load the raw code to/from a file, They exists out of pure convenience only, so people don't have to copy/paste some existing external Lua code from elsewhere. They don't touch the state. The state is touched when saving/loading from the host, e.g. saving/loading a preset.

It is thus best to monitor the saving directory (and its state.ttl) while saving from the host to grok the mechanisms behind state saving/loading.

I'll be happy to hear how I can improve the documentation to make it better understandable...

**Comment by ventosus** [comment] 2018-02-21 20:42
thanks for reporting

fixed in c69a7f24519e892494d06144abf944b2e75fa7e8

**Comment by milkmiruku** [comment] 2018-02-22 04:15
The bug is still there; clicking on anywhere else in Moony then back to the Editor and the position resets to the top of the file.

**Comment by ventosus** [comment] 2018-02-22 07:06
Clicking anywhere else changes the focus. Clicking back on the editor field puts the cursor at the end of the clicked line. This is expected behaviour, isn't it? The bug was about restoring focus to pre-filedialog active editor fields.

**Comment by milkmiruku** [comment] 2018-02-22 07:49
(The bug is also "... I realise now, the text position actually resets every time I click back into the Editor.")

"Clicking back on the editor field puts the cursor at the end of the clicked line. This is expected behaviour, isn't it?"

I guess the expected behaviour would be to put the cursor at the position clicked, unless the pointer is clicked on a position to the right of the text and to the left of the right edge of the Editor.

Currently, I scroll down so line 10 is the first line showing, click to toggle the log, then click on the 2nd character of the 10th line, the Editor resets to the top and I get the cursor on the 2nd character of the 1st line.

**Comment by ventosus** [comment] 2018-02-24 14:57
> I guess the expected behaviour would be to put the cursor at the position clicked, unless the pointer is clicked on a position to the right of the text and to the left of the right edge of the Editor.

That's exactly what I meant, sorry, was not clear enough

I can reproduce the second bug, the scrolling position seems not be be restored properly upon refocusing, cumbersome, indeed.

You can use the keyboard-shortcuts for now to toggle/clear the Log, so the editor widget won't loose focus.

**Comment by ventosus** [comment] 2018-02-24 16:42
This is a bug in the nuklear toolkit, needs to be fixed upstream.

**Comment by ventosus** [comment] 2018-02-26 20:18
fixed in 83d21d53f1a161278beb71698470468e824908ba

please test

**Closed** 2020-03-29 20:12 UTC
