### ISSUE TITLE
On a second error, GUI reports the previous error message

### ISSUE THREAD

**Issue by milkmiruku** [OpenMusicKontrollers/moony.lv2#6] opened 2018-02-20 21:24 UTC
If there's an error which it gets fixed/removed but there's still a further code mistake, clicking Send will make the GUI [re]report the initial error message.

The console however gets the correct error message.

**Comment by ventosus** [comment] 2018-02-21 06:29
I distantly remember to have fixed that already. Which version do you use?

**Comment by milkmiruku** [comment] 2018-02-22 02:23
Github master. Just built again, c69a7f2, issue still exists.

**Comment by ventosus** [comment] 2018-02-24 14:39
I cannot reproduce this.

Which host do you use?

Do you know where the errors originate from?
* while lexing/parsing?
* while running?
* while saving/restoring?

Do you have a non-working example I could try (with instructions to trigger the errors)?

**Comment by ventosus** [comment] 2018-02-27 19:14
thanks for reporting

fixed in fc1e8ab5ddcbaaefe997fbe0762d39db5b59a71e

**Closed by ventosus** 2018-02-27 19:14 UTC
